# Generated by Django 4.0.3 on 2022-03-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('film_id', models.DecimalField(decimal_places=1, max_digits=10, primary_key=True, serialize=False)),
                ('film_titre', models.CharField(max_length=124)),
                ('film_date', models.DateField()),
                ('film_type', models.CharField(max_length=32)),
                ('film_acteurs', models.CharField(max_length=124)),
                ('film_moy_note', models.DecimalField(decimal_places=1, max_digits=2)),
                ('film_platforme', models.CharField(max_length=64)),
                ('film_resume', models.TextField()),
                ('film_statut', models.CharField(max_length=16)),
                ('film_date_ajout', models.DateField()),
                ('film_par_qui', models.CharField(max_length=32)),
                ('film_liens', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='statut',
            fields=[
                ('statut_id', models.DecimalField(decimal_places=1, max_digits=5, primary_key=True, serialize=False)),
                ('statut_label', models.CharField(max_length=124)),
                ('film_titre', models.CharField(max_length=124)),
                ('user_name', models.CharField(max_length=64)),
                ('user_id', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
