# Generated by Django 4.0.3 on 2022-03-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfilms', '0003_remove_statut_user_id_alter_film_id_alter_statut_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statut',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
