# Generated by Django 4.0.3 on 2022-03-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfilms', '0004_alter_film_id_alter_statut_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='acteurs',
        ),
        migrations.RemoveField(
            model_name='film',
            name='date',
        ),
        migrations.RemoveField(
            model_name='film',
            name='date_ajout',
        ),
        migrations.RemoveField(
            model_name='film',
            name='liens',
        ),
        migrations.RemoveField(
            model_name='film',
            name='moy_note',
        ),
        migrations.RemoveField(
            model_name='film',
            name='par_qui',
        ),
        migrations.RemoveField(
            model_name='film',
            name='platforme',
        ),
        migrations.RemoveField(
            model_name='film',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='film',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='film',
            name='type',
        ),
    ]
