# Generated by Django 4.0.3 on 2022-03-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfilms', '0005_remove_film_acteurs_remove_film_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='acteurs',
            field=models.CharField(max_length=124, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='date_ajout',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='film',
            name='liens',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='moy_note',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='par_qui',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='platforme',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='resume',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='statut',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='type',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
