# Generated by Django 4.0.3 on 2022-03-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfilms', '0007_alter_film_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='platforme',
            new_name='plateforme',
        ),
        migrations.AlterField(
            model_name='film',
            name='par_qui',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
